# Application
baseUrl=https://qe-grc.vakilsearch.com/grc/login
browser=chrome
headless=false

# Timeout settings
implicitWait=10
explicitWait=20
pageLoadTimeout=30
# Report
report.path=target/extent-report/extent-report.html

# Screenshot toggles
screenshot.on.pass=true
screenshot.on.skip=true

# Login credentials
email=demo3434343@gmail.com
otp=000000

#WebHook(Google chat)
chatspace=https://chat.googleapis.com/v1/spaces/AAQAXOiSU7Y/messages?key=AIzaSyDdI0hCZtE6vySjMm-WEfRq3CPzqKqqsHI&token=NMCMdf2ZzBauM_4I1-maUK08QYXSDBURzyFw0O7GmyM

#Jenkins Allure Report Url
reportUrl=http://192.168.5.202:8080/job/Zolvit-QE-Tests/allure/
