# Application
baseUrl=https://qe-grc.vakilsearch.com/grc/login
browser=chrome
headless=false

# Timeout settings
implicitWait=10
explicitWait=20
pageLoadTimeout=30
# Report
report.path=target/extent-report/extent-report.html

# Screenshot toggles
screenshot.on.pass=true
screenshot.on.skip=true

# Login credentials
email=demo3434343@gmail.com
otp=000000


